### ISSUE TITLE
Optimization for Spectrum2

### ISSUE THREAD

**Issue by TomTheDragon** [fcwill/fchat-pidgin#16] opened 2015-02-22 23:08 UTC
I was trying to use the fchat-pidgin with Spectrum2 to create a F-Chat jabber transport but i just get errors (symbol lookup error) when i try to load the plugin. I dont have this problem with any of the other "non-standard" plugins i use.

**Comment by fcwill** [comment] 2015-02-23 01:12
Could you be more specific about the errors you're getting (maybe provide us with logs, ...)?

**Comment by TomTheDragon** [comment] 2015-02-23 01:16
I am getting this error right here if i try to load the plugin:

Starting "/etc/spectrum2/transports/flist.cfg": OK
/usr/bin/spectrum2_libpurple_backend: symbol lookup error: /usr/lib/purple-2/flist.so: undefined symbol: gtk_imhtml_class_register_protocol
/usr/bin/spectrum2_libpurple_backend: symbol lookup error: /usr/lib/purple-2/flist.so: undefined symbol: gtk_imhtml_class_register_protocol
/usr/bin/spectrum2_libpurple_backend: symbol lookup error: /usr/lib/purple-2/flist.so: undefined symbol: gtk_imhtml_class_register_protocol
...(the last line repeats over and over again)

**Comment by vobe** [comment] 2015-02-23 06:51
You must use

    make FLIST_PURPLE_ONLY=1

To compile the plugin without the pidgin-specific calls. (You might need to run `make clean` first)
This should probably be better documented

**Comment by TomTheDragon** [comment] 2015-02-23 18:04
I tried to compile it with "FLIST_PURPLE_ONLY=1" and it seems to work. I can connect if i enter my account like "username:charname" and i can send massages just fine.

But i dont see all of my buddies and i get many errors in the console like this:
(process:10708): Json-CRITICAL **: json_object_get_string_member: assertion `node != NULL' failed
(process:11268): Json-CRITICAL **: json_object_get_int_member: assertion `node != NULL' failed
(process:10708): Json-CRITICAL **: json_array_get_length: assertion `array != NULL' failed

**Comment by vobe** [comment] 2015-02-23 19:50
I get this error a lot too, it doesn't look too serious, but maybe it's worth a look sometime. For your buddy issue, the plugin has options that govern whether or not you load friends and bookmarks from the server, did you enable them in spectrum ?

**Comment by TomTheDragon** [comment] 2015-02-23 21:04
Oh yes sorry i forgot about the setting thing.. but the problem is that the libpurple module of spectrum2 is really simple. So you can just enter username and passwort, thats all. I am not sure if there is something you can change on the plugin to add another field.

**Comment by vobe** [comment] 2015-02-23 21:31
From what I can grok through the Spectrum source code you should be able to set options for your purple account in the spectrum config file.

The format, although I'm not 100% sure of it, seems to be
[purple]
sync_bookmarks = true
sync_friends = true

and so on for each flist setting you'd need to set
You might need to ask the Spectrum devs for help on how exactly to set account options for purple accounts, because it definitely looks possible.

Another option, of course, is for you to hardcode the default option settings in f-list.c, you should look around line 531

**Comment by vobe** [comment] 2015-02-25 06:51
Tom confirmed that setting the Spectrum config worked. I fixed the doc so I'm closing this issue. If other problems arise, it would be best to track them each in their own issue.

**Closed by vobe** 2015-02-25 06:51 UTC
