### ISSUE TITLE
Feature change: modify /me posts to resemble non-/me posts

### ISSUE THREAD

**Issue by Brickcaster** [fcwill/fchat-pidgin#94] opened 2016-02-13 18:37 UTC
I would like the ability to have names colored (pink/blue/etc) when they use /me to make a post.  In addition, I want the ability to see the user right click menu on their user name like when I right click a non-/me username chat message.

**Comment by fcwill** [comment] 2016-02-18 12:59
IIRC this wasn't as easy as we thought in the beginning.
@syldrathecat should know more about that!

**Comment by fcwill** [comment] 2016-03-28 11:08
Just noticed that this is a duplicate of #80

**Closed by fcwill** 2016-03-28 11:08 UTC
Labels: enhancement, help wanted
